name: rosetta
description: Desktop-first ARB (Application Resource Bundle) translation management tool for Flutter developers
publish_to: none

version: 0.1.0+1

homepage: https://github.com/ilia-korolev/rosetta
repository: https://github.com/ilia-korolev/rosetta
issue_tracker: https://github.com/ilia-korolev/rosetta/issues

topics:
  - arb
  - translation
  - localization
  - i18n
  - l10n

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.8"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management & Dependency Injection
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0

  # Data Serialization & Code Generation
  dart_mappable: ^4.6.0
  json_annotation: ^4.9.0

  # Routing & Navigation
  go_router: ^16.1.0

  # Internationalization
  intl: ^0.20.2

  # File Operations & System Integration
  csv: ^6.0.0
  file_picker: ^10.2.4
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.3.4
  watcher: ^1.1.2

  # UI Components
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing Framework
  bloc_test: ^10.0.0
  mocktail: ^1.0.4

  # Code Generation
  build_runner: ^2.6.0
  dart_mappable_builder: ^4.6.0
  json_serializable: ^6.10.0

  # Code Quality & Linting
  flutter_lints: ^6.0.0
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true

  # Application assets
  assets:
    - assets/images/
    - assets/icons/
    - example_app_en.arb
    - example_app_es.arb

  # Generate localization files
  generate: true
