name: rosetta
description: Desktop-first ARB (Application Resource Bundle) translation management tool for Flutter developers
publish_to: none

version: 0.1.0+1

homepage: https://github.com/dev-ikorolev/rosetta
repository: https://github.com/dev-ikorolev/rosetta
issue_tracker: https://github.com/dev-ikorolev/rosetta/issues

topics:
  - arb
  - translation
  - i18n
  - localization
  - flutter
  - desktop

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.32.8"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management & Dependency Injection
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0

  # Data Serialization & Code Generation
  dart_mappable: ^4.2.2
  json_annotation: ^4.9.0

  # Routing & Navigation
  go_router: ^14.2.7

  # Internationalization
  intl: ^0.20.2

  # File Operations & System Integration
  csv: ^6.0.0
  file_picker: ^8.1.2
  path: ^1.9.0
  path_provider: ^2.1.4
  watcher: ^1.1.0

  # UI Components
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing Framework
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

  # Code Generation
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.2.3
  json_serializable: ^6.8.0

  # Code Quality & Linting
  flutter_lints: ^5.0.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true

  # Application assets
  assets:
    - assets/images/
    - assets/icons/
    - example_app_en.arb
    - example_app_es.arb

  # Generate localization files
  generate: true
